---
name: Accuracy Request
description: Provide information around the nature of the inaccuracy.
body:
- type: textarea
  attributes:
    label: File
    placeholder: "Examples: programming-fundamentals/loops/index.md"
  validations:
    required: true
- type: textarea
  attributes:
    label: Inaccurate statement
    placeholder: "Examples: The text reads: 'There are two types of loops in JavaScript while and for."
  validations:
    required: true
- type: textarea
  attributes:
    label: Correction
    placeholder: "Examples: according to MDN JavaScript provides: for, do...while, while, for...in, for...of."
  validations:
    required: true
- type: textarea
  attributes:
    label: Sources
    placeholder: "Examples: MDN via https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Loops_and_iteration"
  validations:
    required: true