---
name: Bug
description: Provide information around the nature of the encountered bug.
body:
- type: markdown
  attributes:
    value: "# Bug Form"
- type: markdown
  attributes:
    value: |
      Please provide information around the nature of the bug you encountered by filling out the remainder of this form. The more information you provide us, the more likely we will be able to resolve the issue.
- type: textarea
  attributes:
    label: File
    placeholder: "Examples: contributing/edit-page/index.md"
  validations:
    required: true
- type: textarea
  attributes:
    label: Nature of Bug
    placeholder: "Examples: link with text 'Click here to learn more' is broken; button with text 'Click for Answer' is broken; code block contains code that doesn't run"
  validations:
    required: true
- type: textarea
  attributes:
    label: More information
    placeholder: "Example: please provide any additional relevant information including the expected behavior the bug may be inhibiting."
- type: markdown
  attributes:
    value: "# Thank You"
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to help us in improving this course. You rock!