---
name: Feature Request
description: Please let us know what feature should be added.
body:
- type: textarea
  attributes:
    label: Feature Short Description
    placeholder: "Examples: Git rebase example."
  validations:
    required: true
- type: textarea
  attributes:
    label: Feature Long Description
    placeholder: "Examples: The Git chapter mentioned git rebase as a viable merge strategy, however there were no examples on performing a git rebase."
- type: textarea
  attributes:
    label: Where Should the Feature Be added
    placeholder: "The example should be added as a new section after the git merge section. It could be titled git rebase."